name: AutomationTesting

on:
 schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
 workflow_dispatch:
   inputs:
      run_tests:
        description: 'Run Single Test or All Tests'
        required: true
        default: 'all'  # 'single' to run a specific test, 'all' to run all tests
      test_class:
        description: 'Test class to run (only required if run_tests is "single")'
        type: choice
        options:
          - GreeterTest.java
          - RunnerTest.java
        required: false  # This will only be used if 'run_tests' is 'single'

jobs:
  build_test_publish:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
         ${{ runner.os }}-maven-
    
    - name: Run all tests (default behavior)
      if: ${{ github.event.inputs.run_tests == 'all' }}
      run: mvn clean test -B

    - name: Run single test
      if: ${{ github.event.inputs.run_tests == 'single' && github.event.inputs.test_class != '' }}
      run: mvn -Dtest=${{ github.event.inputs.test_class }} test -B
 
    #- name: Build and run tests with Maven
      #run: mvn clean test -B  # 'clean' ensures a fresh build, 'test' runs unit tests

   # - name: Build the package (JAR)
      #run: mvn -B package --file pom.xml 

    - name: Listing the target directory
      run: ls -R
      working-directory: ${{ github.workspace }}/target/

    - name: Store build artifacts as artifact
      uses: actions/upload-artifact@v3
      with:
        name: jar-outputs
        path: target/
