name: AutomationTestingBranch

on:
 schedule:
    - cron: '10 11 * * *'  # Runs daily at midnight UTC
 workflow_dispatch:
   inputs:
      run_tests:
        description: 'Run Single Test or All Tests'
        required: true
        default: 'all'  # 'single' to run a specific test, 'all' to run all tests
      test_class:
        description: 'Test class to run (only required if run_tests is "single")'
        type: choice
        options:
          - GreeterTest.java
          - RunnerTest.java
        required: false  # This will only be used if 'run_tests' is 'single'

jobs:
  build_test_publish:
    runs-on: ubuntu-latest 
    steps:
    - name: Checksout the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
         ${{ runner.os }}-maven-

    - name: Set environment variable based on trigger type (on-schedule vs workflow_dispatch)
      run: |
        # For on-schedule event, default to 'all' tests
        if [[ "${{ github.event_name }}" == "schedule" ]]; then
          echo "RUN_TESTS=all" >> $GITHUB_ENV
        else
          echo "RUN_TESTS=${{ github.event.inputs.run_tests }}" >> $GITHUB_ENV
          if [[ "${{ github.event.inputs.run_tests }}" == "single" ]]; then
            echo "TEST_CLASS=${{ github.event.inputs.test_class }}" >> $GITHUB_ENV
          fi
        fi

    - name: Run all tests (default behavior if RUN_TESTS=all)
      if: ${{ env.RUN_TESTS == 'all' }}
      run: mvn clean test -B

    - name: Run single test (if RUN_TESTS=single)
      if: ${{ env.RUN_TESTS == 'single' }}
      run: mvn -Dtest=${{ env.TEST_CLASS }} test -B

    - name: Upload Summary
      uses: actions/upload-artifact@v3
      with:
       name: summary-artifact
       path: ./Test.html
   
    - name: Print URL for index.html
      run: |
        #test_report_url="https://raw.githubusercontent.com/mspriya92/JavaApp/main/index.html"
        test_report_url="https://mspriya92.github.io/JavaApp/Test.html"
        #test_report_url="${{ github.server_url }}/${{ github.repository }}/Test.html"
        #https://mspriya92.github.io/JavaApp/
        echo "Test Report URL: $test_report_url" >> $GITHUB_STEP_SUMMARY
        
    - name: Send Email with Test Report
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Test Report"
          to: divya.prabhavathi@digitalsoftwareinc.in
          from: priyadarshini.mahalingam@digitalsoftwareinc.in  
          body: "The test report is attached."
          attachments: Test.html
        
    #- name: Display summary with artifact link
      #run: |
          #echo "## Summary" >> $env:GITHUB_STEP_SUMMARY
          #echo "The test report can be downloaded [here](./artifacts/index-html-artifact/index.html)." >> $GITHUB_STEP_SUMMARY  
    
   #- name: Display summary in the summary
      #run: |
          #echo "## Summary" >> $env:GITHUB_STEP_SUMMARY
          #cat index.html >> $GITHUB_STEP_SUMMARY
          #cat index.txt >> $GITHUB_STEP_SUMMARY

    #- name: Output current time
      #run: |
        #echo "Current time: $(date)"
 
  
