name: AutomationTesting
on:
 workflow_dispatch:
   inputs:
      test_class:
        description: 'Test class to run (only required if run_tests is "single")'
        type: choice
        options:
          - Homepage
          - AllAccounts
        required: false  # This will only be used if 'run_tests' is 'single'
 
jobs:
  Testcase-run:
    runs-on: auto-test  
 
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
 
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
         ${{ runner.os }}-maven-

    - name: Set env variable based on trigger type
      run: |
         if [ "${{ github.event.inputs.test_class }}" == "Homepage" ]; then
           echo "If condition working"
          else
           echo "If condition not working"
         fi
	 
    - name: Upload Summary
      uses: actions/upload-artifact@v3
      with:
       name: summary-artifact
       path: ./Test.html
	   
